### ISSUE TITLE
1- List with concerts

### ISSUE THREAD

**Issue by frederikebruendermann** [frederikebruendermann/capstone-project#1]
# Value proposition (user story)

As a **user**
I want to see a **list of concerts in Bremen**
so that I can **I have an overview** 

# Description (text, scribble, wireframe, design)
![US1](https://user-images.githubusercontent.com/82148810/121338092-78a13f00-c91d-11eb-9459-a9b46e9b78ad.png)

# Acceptance criteria

- [x] Concerts should show artist, date and location
- [x] list should be scrollable 

# Complexity (low, medium, high)
low

# Tasks
- [x] create feature branch
- [x] Build Title component
- [x] Build basic card component in storybook
- [x] Build SearchPage component in storybook
- [x] write tests for both sides
- [x] add cards to SearchPage
- [x] write array with test content
- [x] add global styles
- [x] add searchPage to App.js

**Comment by frederikebruendermann** [comment]
***Description (Text, Scribble, Wireframe, Design)***
