### ISSUE TITLE
Next Concerts

### ISSUE THREAD

**Issue by frederikebruendermann** [frederikebruendermann/capstone-project#11]
# Value proposition (user story)
As a **user**
I want to **see the next concerts on first view**
to get **my personal overview**

# Description (text, scribble, wireframe, design)
![ConcertLife_Scribble_US4_0306(1)](https://user-images.githubusercontent.com/82148810/120697518-1de78d80-c4ae-11eb-8e7d-569323590be7.png)

# Acceptance criteria
- [ ] button to add concert to calender
- [ ] calender dates must be saved
- [ ] the next concerts on the home page should be in the right order

# Complexity (low, medium, high)
medium

# Tasks
- [ ] create feature branch
- [ ] create button for calender entry
- [ ] add button on concert Detail Page to save concerts to calender
- [ ] use local storage (or a backend?)
- [ ] show next 5 concerts on the top of the home page
- [ ] write tests for the components
