### ISSUE TITLE
3- City Selection

### ISSUE THREAD

**Issue by frederikebruendermann** [frederikebruendermann/capstone-project#2]
# Value proposition (user story)
As a **user**
I want to **choose a city**
so that I can **get concerts near by** 

# Description (text, scribble, wireframe, design)
![US3](https://user-images.githubusercontent.com/82148810/121338344-b56d3600-c91d-11eb-8c06-19046ed8ac81.png)

# Acceptance criteria
- [x] user should type in a city to search for
- [x] concerts should be shown (next ones first)

# Complexity (low, medium, high)
medium 

# Tasks
- [x] Create feature branch
- [x] Fetch API
- [x] built Button Search component
- [x] connect Button and API
- [x] write a test for the new component and the fetch

**Comment by frederikebruendermann** [comment]
# Value proposition (user story)

# Description (text, scribble, wireframe, design)

# Acceptance criteria

# Complexity (low, medium, high)

# Tasks
