### ISSUE TITLE
2- Concert Details

### ISSUE THREAD

**Issue by frederikebruendermann** [frederikebruendermann/capstone-project#3]
# Value proposition (user story)
As a **user**
I want to **get more Details**
so that I can **made a decision**

# Description (text, scribble, wireframe, design)
![US 2](https://user-images.githubusercontent.com/82148810/121338163-8787f180-c91d-11eb-9734-c601eb5ce350.png)
![US2 a](https://user-images.githubusercontent.com/82148810/121340182-9a032a80-c91f-11eb-995c-344ed0c03e1a.png)

# Acceptance criteria

- [x] Every concert should get a DetailPage by clicking on it
- [x] there should be the location, start time and ticket link 
- [x] pictures are shown on the top
- [x] details on the bottom below 

# Complexity (low, medium, high)
medium

# Tasks

- [x] create feature branch
- [x] create DetailPage
- [x] integrate image, start time, location and ticketlink 
- [x] update card component with picture and onclick function
- [x] update list component
- [x] test new page
