### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by frederikebruendermann** [frederikebruendermann/capstone-project#4]
# Value proposition (user story)
As a **user**
I want to **bookmark my favourite concerts**
to get **my personal overview**

# Description (text, scribble, wireframe, design)
<img width="323" alt="Bildschirmfoto 2021-06-23 um 13 57 59" src="https://user-images.githubusercontent.com/82148810/123092706-1111e600-d42b-11eb-8a6d-130e92c9e81e.png">

# Acceptance criteria
- [x] every concert card should get a bookmark
- [x] the bookmark should be togglebar
- [x] the bookmark is on the right top corner of the detailpage
- [x] the bookmark changes color on toggle

# Complexity (low, medium, high)
low 

# Tasks
- [x] create feature branch
- [x] build bookmark component
- [x] update concert details with bookmark
