### ISSUE TITLE
BookmarkPage & Nav

### ISSUE THREAD

**Issue by frederikebruendermann** [frederikebruendermann/capstone-project#5]
# Value proposition (user story)
As a **user**
I want to **see all my favourite concerts**
to find **them easier**

# Description (text, scribble, wireframe, design)
![ConcertLife_Scribble_US5_0306](https://user-images.githubusercontent.com/82148810/123173417-dafe5180-d47e-11eb-885d-ab931ea0dca5.png)

# Acceptance criteria

- [x] page should show all bookmarked concerts
- [x] sorted by date, next should be on top
- [x] past concerts should be deleted
- [x] BookmarkPage and SearchPage are shown by clicking the symbol in Nav

# Complexity (low, medium, high)
medium

# Tasks
- [x] create a feature branch
- [x] filter concert cards by bookmark
- [x] add page with all bookmarks (future Start Page (!))
- [x] write test for filter 
- [x] build Nav component
- [x] write test for component 
- [x] update pages
